var hierarchy =
[
    [ "tmc51x0::AccelerationValue", "structtmc51x0_1_1AccelerationValue.html", null ],
    [ "BackAndForthMotion", "classBackAndForthMotion.html", null ],
    [ "tmc51x0_test_config::BoardConfig_TMC51x0_BOB", "structtmc51x0__test__config_1_1BoardConfig__TMC51x0__BOB.html", null ],
    [ "tmc51x0_test_config::BoardConfig_TMC51x0_EVAL", "structtmc51x0__test__config_1_1BoardConfig__TMC51x0__EVAL.html", null ],
    [ "FatigueTest::BoundsFinderConfig", "structFatigueTest_1_1BoundsFinderConfig.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Homing::BoundsOptions", "structtmc51x0_1_1TMC51x0_1_1Homing_1_1BoundsOptions.html", null ],
    [ "FatigueTest::BoundsResult", "structFatigueTest_1_1BoundsResult.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Homing::BoundsResult", "structtmc51x0_1_1TMC51x0_1_1Homing_1_1BoundsResult.html", null ],
    [ "tmc51x0::CHOPCONF_Register", "uniontmc51x0_1_1CHOPCONF__Register.html", null ],
    [ "tmc51x0::ChopperConfig", "structtmc51x0_1_1ChopperConfig.html", null ],
    [ "tmc51x0::CommInterface< Derived >", "classtmc51x0_1_1CommInterface.html", [
      [ "tmc51x0::SpiCommInterface< Esp32SPI >", "classtmc51x0_1_1SpiCommInterface.html", [
        [ "Esp32SPI", "classEsp32SPI.html", null ]
      ] ],
      [ "tmc51x0::SpiCommInterface< Derived >", "classtmc51x0_1_1SpiCommInterface.html", null ],
      [ "tmc51x0::UartCommInterface< Derived >", "classtmc51x0_1_1UartCommInterface.html", null ]
    ] ],
    [ "tmc51x0::CommInterface< Esp32SPI >", "classtmc51x0_1_1CommInterface.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Communication", "structtmc51x0_1_1TMC51x0_1_1Communication.html", null ],
    [ "ConfigAckPayload", "structConfigAckPayload.html", null ],
    [ "tmc51x0::ConfigBuilder", "classtmc51x0_1_1ConfigBuilder.html", null ],
    [ "ConfigPayload", "structConfigPayload.html", null ],
    [ "tmc51x0::COOLCONF_Register", "uniontmc51x0_1_1COOLCONF__Register.html", null ],
    [ "tmc51x0::CoolStepConfig", "structtmc51x0_1_1CoolStepConfig.html", null ],
    [ "tmc51x0::DCCTRL_Register", "uniontmc51x0_1_1DCCTRL__Register.html", null ],
    [ "tmc51x0::DcStepConfig", "structtmc51x0_1_1DcStepConfig.html", null ],
    [ "tmc51x0::Diag0Config", "structtmc51x0_1_1Diag0Config.html", null ],
    [ "tmc51x0::Diag1Config", "structtmc51x0_1_1Diag1Config.html", null ],
    [ "tmc51x0::DriverConfig", "structtmc51x0_1_1DriverConfig.html", null ],
    [ "tmc51x0::DRV_CONF_Register", "uniontmc51x0_1_1DRV__CONF__Register.html", null ],
    [ "tmc51x0::DRV_STATUS_Register", "uniontmc51x0_1_1DRV__STATUS__Register.html", null ],
    [ "tmc51x0::ENC_STATUS_Register", "uniontmc51x0_1_1ENC__STATUS__Register.html", null ],
    [ "tmc51x0::ENCMODE_Register", "uniontmc51x0_1_1ENCMODE__Register.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Encoder", "structtmc51x0_1_1TMC51x0_1_1Encoder.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_CoreDriverTestRig::Encoder", "structtmc51x0__test__config_1_1PlatformConfig__CoreDriverTestRig_1_1Encoder.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_FatigueTestRig::Encoder", "structtmc51x0__test__config_1_1PlatformConfig__FatigueTestRig_1_1Encoder.html", null ],
    [ "tmc51x0::EncoderConfig", "structtmc51x0_1_1EncoderConfig.html", null ],
    [ "ErrorPayload", "structErrorPayload.html", null ],
    [ "Esp32SpiPinConfig", "structEsp32SpiPinConfig.html", null ],
    [ "Esp32TmcMutex", "classEsp32TmcMutex.html", null ],
    [ "EspNowHeader", "structEspNowHeader.html", null ],
    [ "EspNowPacket", "structEspNowPacket.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Events", "structtmc51x0_1_1TMC51x0_1_1Events.html", null ],
    [ "tmc51x0::ExternalClockConfig", "structtmc51x0_1_1ExternalClockConfig.html", null ],
    [ "FatigueTest::FatigueTestMotion", "classFatigueTest_1_1FatigueTestMotion.html", null ],
    [ "tmc51x0::SpiCommand::Frame", "uniontmc51x0_1_1SpiCommand_1_1Frame.html", null ],
    [ "tmc51x0::UartFrame::Frame", "uniontmc51x0_1_1UartFrame_1_1Frame.html", null ],
    [ "tmc51x0::GCONF_Register", "uniontmc51x0_1_1GCONF__Register.html", null ],
    [ "tmc51x0::GlobalConfig", "structtmc51x0_1_1GlobalConfig.html", null ],
    [ "tmc51x0::GSTAT_Register", "uniontmc51x0_1_1GSTAT__Register.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::HardResetOptions", "structtmc51x0_1_1TMC51x0_1_1HardResetOptions.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Homing::HomeConfig", "structtmc51x0_1_1TMC51x0_1_1Homing_1_1HomeConfig.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Homing", "structtmc51x0_1_1TMC51x0_1_1Homing.html", null ],
    [ "tmc51x0::HomingSettingsCache", "structtmc51x0_1_1HomingSettingsCache.html", null ],
    [ "FatigueTest::IBoundsFinder", "classFatigueTest_1_1IBoundsFinder.html", [
      [ "FatigueTest::EncoderBoundsFinderImpl< test_rig >", "classFatigueTest_1_1EncoderBoundsFinderImpl.html", null ],
      [ "FatigueTest::StallGuardBoundsFinderImpl< test_rig >", "classFatigueTest_1_1StallGuardBoundsFinderImpl.html", null ]
    ] ],
    [ "tmc51x0::IHOLD_IRUN_Register", "uniontmc51x0_1_1IHOLD__IRUN__Register.html", null ],
    [ "tmc51x0::InputStatus", "structtmc51x0_1_1InputStatus.html", null ],
    [ "integral_constant", null, [
      [ "std::tuple_size< tmc51x0::Result< T > >", "structstd_1_1tuple__size_3_01tmc51x0_1_1Result_3_01T_01_4_01_4.html", null ],
      [ "std::tuple_size< tmc51x0::Result< void > >", "structstd_1_1tuple__size_3_01tmc51x0_1_1Result_3_01void_01_4_01_4.html", null ]
    ] ],
    [ "tmc51x0::TMC51x0< CommType >::Io", "structtmc51x0_1_1TMC51x0_1_1Io.html", null ],
    [ "tmc51x0::IOIN_Register", "uniontmc51x0_1_1IOIN__Register.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_CoreDriverTestRig::Mechanical", "structtmc51x0__test__config_1_1PlatformConfig__CoreDriverTestRig_1_1Mechanical.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_FatigueTestRig::Mechanical", "structtmc51x0__test__config_1_1PlatformConfig__FatigueTestRig_1_1Mechanical.html", null ],
    [ "tmc51x0::MechanicalSystem", "structtmc51x0_1_1MechanicalSystem.html", null ],
    [ "tmc51x0::MicrostepChangeOptions", "structtmc51x0_1_1MicrostepChangeOptions.html", null ],
    [ "tmc51x0_test_config::TestConfig_17HS4401S::Motion", "structtmc51x0__test__config_1_1TestConfig__17HS4401S_1_1Motion.html", null ],
    [ "tmc51x0_test_config::TestConfig_AppliedMotion_5034::Motion", "structtmc51x0__test__config_1_1TestConfig__AppliedMotion__5034_1_1Motion.html", null ],
    [ "tmc51x0_test_config::TestConfigAccessor< motor_type >::Motion", "structtmc51x0__test__config_1_1TestConfigAccessor_1_1Motion.html", null ],
    [ "tmc51x0_test_config::MotorConfig_17HS4401S", "structtmc51x0__test__config_1_1MotorConfig__17HS4401S.html", null ],
    [ "tmc51x0_test_config::MotorConfig_17HS4401S_Direct", "structtmc51x0__test__config_1_1MotorConfig__17HS4401S__Direct.html", null ],
    [ "tmc51x0_test_config::MotorConfig_AppliedMotion_5034_369", "structtmc51x0__test__config_1_1MotorConfig__AppliedMotion__5034__369.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::MotorControl", "structtmc51x0_1_1TMC51x0_1_1MotorControl.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::MotorCurrentDebugInfo", "structtmc51x0_1_1TMC51x0_1_1MotorCurrentDebugInfo.html", null ],
    [ "tmc51x0::MotorSpec", "structtmc51x0_1_1MotorSpec.html", null ],
    [ "tmc51x0::MSCURACT_Register", "uniontmc51x0_1_1MSCURACT__Register.html", null ],
    [ "tmc51x0::MSLUTSEL_Register", "uniontmc51x0_1_1MSLUTSEL__Register.html", null ],
    [ "tmc51x0::NODECONF_Register", "uniontmc51x0_1_1NODECONF__Register.html", null ],
    [ "tmc51x0::OFFSET_READ_Register", "uniontmc51x0_1_1OFFSET__READ__Register.html", null ],
    [ "OptionParser::OptionDef", "structOptionParser_1_1OptionDef.html", null ],
    [ "OptionParser", "classOptionParser.html", null ],
    [ "tmc51x0::OTP_PROG_Register", "uniontmc51x0_1_1OTP__PROG__Register.html", null ],
    [ "tmc51x0::OTP_READ_Register", "uniontmc51x0_1_1OTP__READ__Register.html", null ],
    [ "ParsedCommand", "structParsedCommand.html", null ],
    [ "tmc51x0::PinActiveLevels", "structtmc51x0_1_1PinActiveLevels.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_CoreDriverTestRig", "structtmc51x0__test__config_1_1PlatformConfig__CoreDriverTestRig.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_FatigueTestRig", "structtmc51x0__test__config_1_1PlatformConfig__FatigueTestRig.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::PowerStage", "structtmc51x0_1_1TMC51x0_1_1PowerStage.html", null ],
    [ "tmc51x0::PowerStageParameters", "structtmc51x0_1_1PowerStageParameters.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Printer", "structtmc51x0_1_1TMC51x0_1_1Printer.html", null ],
    [ "ProtoEvent", "structProtoEvent.html", null ],
    [ "tmc51x0::PWM_AUTO_Register", "uniontmc51x0_1_1PWM__AUTO__Register.html", null ],
    [ "tmc51x0::PWM_SCALE_Register", "uniontmc51x0_1_1PWM__SCALE__Register.html", null ],
    [ "tmc51x0::PWMCONF_Register", "uniontmc51x0_1_1PWMCONF__Register.html", null ],
    [ "tmc51x0::RAMP_STAT_Register", "uniontmc51x0_1_1RAMP__STAT__Register.html", null ],
    [ "tmc51x0::RampConfig", "structtmc51x0_1_1RampConfig.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::RampControl", "structtmc51x0_1_1TMC51x0_1_1RampControl.html", null ],
    [ "RawMsg", "structRawMsg.html", null ],
    [ "tmc51x0::ReferenceSwitchConfig", "structtmc51x0_1_1ReferenceSwitchConfig.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_CoreDriverTestRig::ReferenceSwitches", "structtmc51x0__test__config_1_1PlatformConfig__CoreDriverTestRig_1_1ReferenceSwitches.html", null ],
    [ "tmc51x0_test_config::PlatformConfig_FatigueTestRig::ReferenceSwitches", "structtmc51x0__test__config_1_1PlatformConfig__FatigueTestRig_1_1ReferenceSwitches.html", null ],
    [ "tmc51x0::Result< T >", "classtmc51x0_1_1Result.html", null ],
    [ "tmc51x0::Result< void >", "classtmc51x0_1_1Result_3_01void_01_4.html", null ],
    [ "Settings", "structSettings.html", null ],
    [ "tmc51x0::SHORT_CONF_Register", "uniontmc51x0_1_1SHORT__CONF__Register.html", null ],
    [ "tmc51x0::SpiCommand", "structtmc51x0_1_1SpiCommand.html", null ],
    [ "tmc51x0::SpiResponse", "structtmc51x0_1_1SpiResponse.html", null ],
    [ "tmc51x0::SpiStatus", "structtmc51x0_1_1SpiStatus.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::StallGuard", "structtmc51x0_1_1TMC51x0_1_1StallGuard.html", null ],
    [ "tmc51x0_test_config::TestConfig_17HS4401S::StallGuard", "structtmc51x0__test__config_1_1TestConfig__17HS4401S_1_1StallGuard.html", null ],
    [ "tmc51x0_test_config::TestConfig_AppliedMotion_5034::StallGuard", "structtmc51x0__test__config_1_1TestConfig__AppliedMotion__5034_1_1StallGuard.html", null ],
    [ "tmc51x0_test_config::TestConfigAccessor< motor_type >::StallGuard", "structtmc51x0__test__config_1_1TestConfigAccessor_1_1StallGuard.html", null ],
    [ "tmc51x0::StallGuardConfig", "structtmc51x0_1_1StallGuardConfig.html", null ],
    [ "tmc51x0::StallGuardTuningResult", "structtmc51x0_1_1StallGuardTuningResult.html", null ],
    [ "FatigueTest::FatigueTestMotion::Status", "structFatigueTest_1_1FatigueTestMotion_1_1Status.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Status", "structtmc51x0_1_1TMC51x0_1_1Status.html", null ],
    [ "StatusPayload", "structStatusPayload.html", null ],
    [ "tmc51x0::StealthChopConfig", "structtmc51x0_1_1StealthChopConfig.html", null ],
    [ "tmc51x0::SW_MODE_Register", "uniontmc51x0_1_1SW__MODE__Register.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Switches", "structtmc51x0_1_1TMC51x0_1_1Switches.html", null ],
    [ "tmc51x0_test_config::TestConfig_17HS4401S", "structtmc51x0__test__config_1_1TestConfig__17HS4401S.html", null ],
    [ "tmc51x0_test_config::TestConfig_AppliedMotion_5034", "structtmc51x0__test__config_1_1TestConfig__AppliedMotion__5034.html", null ],
    [ "tmc51x0_test_config::TestConfigAccessor< motor_type >", "structtmc51x0__test__config_1_1TestConfigAccessor.html", null ],
    [ "TestDriverHandle", "structTestDriverHandle.html", null ],
    [ "TestResults", "structTestResults.html", null ],
    [ "tmc51x0_test_config::TestRigConfig< test_rig >", "structtmc51x0__test__config_1_1TestRigConfig.html", null ],
    [ "tmc51x0_test_config::TestRigConfig< TestRigType::TEST_RIG_CORE_DRIVER >", "structtmc51x0__test__config_1_1TestRigConfig_3_01TestRigType_1_1TEST__RIG__CORE__DRIVER_01_4.html", null ],
    [ "tmc51x0_test_config::TestRigConfig< TestRigType::TEST_RIG_FATIGUE >", "structtmc51x0__test__config_1_1TestRigConfig_3_01TestRigType_1_1TEST__RIG__FATIGUE_01_4.html", null ],
    [ "TestTaskContext", "structTestTaskContext.html", null ],
    [ "TestUnitSettings", "structTestUnitSettings.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Thresholds", "structtmc51x0_1_1TMC51x0_1_1Thresholds.html", null ],
    [ "tmc51x0::TMC51x0< CommType >", "classtmc51x0_1_1TMC51x0.html", null ],
    [ "tmc51x0::TMC51x0< Esp32SPI >", "classtmc51x0_1_1TMC51x0.html", null ],
    [ "tmc51x0::TMC51x0DaisyChain< CommType, MaxDevices >", "classtmc51x0_1_1TMC51x0DaisyChain.html", null ],
    [ "tmc51x0::TMC51x0MultiNode< CommType, MaxDevices >", "classtmc51x0_1_1TMC51x0MultiNode.html", null ],
    [ "tmc51x0::TMC51x0PinConfig", "structtmc51x0_1_1TMC51x0PinConfig.html", null ],
    [ "TmcMutexGuard", "classTmcMutexGuard.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::Tuning", "structtmc51x0_1_1TMC51x0_1_1Tuning.html", null ],
    [ "std::tuple_element< 0, tmc51x0::Result< T > >", "structstd_1_1tuple__element_3_010_00_01tmc51x0_1_1Result_3_01T_01_4_01_4.html", null ],
    [ "std::tuple_element< 0, tmc51x0::Result< void > >", "structstd_1_1tuple__element_3_010_00_01tmc51x0_1_1Result_3_01void_01_4_01_4.html", null ],
    [ "std::tuple_element< 1, tmc51x0::Result< T > >", "structstd_1_1tuple__element_3_011_00_01tmc51x0_1_1Result_3_01T_01_4_01_4.html", null ],
    [ "UartCommandParser", "classUartCommandParser.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::UartConfig", "structtmc51x0_1_1TMC51x0_1_1UartConfig.html", null ],
    [ "tmc51x0::UartConfig", "structtmc51x0_1_1UartConfig.html", null ],
    [ "tmc51x0::UartFrame", "structtmc51x0_1_1UartFrame.html", null ],
    [ "UISettings", "structUISettings.html", null ],
    [ "tmc51x0::VelocityValue", "structtmc51x0_1_1VelocityValue.html", null ],
    [ "tmc51x0::TMC51x0< CommType >::WriteOnlyRegisters", "structtmc51x0_1_1TMC51x0_1_1WriteOnlyRegisters.html", null ]
];